### ISSUE TITLE
Batch request and ethereum etl does not work

### ISSUE THREAD

**Issue by ohrab-hacken** [rainshowerLabs/blutgang#17]
**Describe the bug**
I am running latest version of blutgang(0.1.0) on the server and expose it on port 3000. 
Config that I am using:
```
# Config for blutgang goes here
[blutgang]
do_clear = false # Clear the cache DB on startup
address = "0.0.0.0:3000" # Where to bind blutgang to
ma_length = 10 # Moving average length for the latency
sort_on_startup = true # Sort RPCs by latency on startup. Recommended to leave on.
health_check = true # Enable health checking
ttl = 300 # Acceptable time to wait for a response in ms
health_check_ttl = 12000 # Time between health checks in ms

# Sled config
# Sled is the database we use for our cache, for more info check their docs
[sled]
db_path = "./blutgang-cache" # Path to db
mode = "HighThroughput" # sled mode. Can be HighThroughput/LowSpace
cache_capacity = 1000000000 # Cache size in bytes. Doesn't matter too much as you OS should also be caching.
compression = false # Use zstd compression. Reduces size 60-70%, and increases CPU and latency by around 10% for db writes and 2% for reads
print_profile = false # Print DB profile when dropped. Doesn't do anything for now.
flush_every_ms = 24000 # Frequency of flushes in ms

# Add seperate RPCs as TOML tables
# DO NOT name an rpc `blutgang` or `sled`
[private]
url = "http://eth.hckn.dev:8545" # RPC url
max_consecutive = 5 # The maximum ammount of time we can use this rpc in a row.
max_per_second = 0 # Max ammount of querries per second. Doesn't do anything for now.
```
Following curl request to blutgang is success:
```
curl -X POST -i -H 'Content-type:application/json'  http://10.1.194.183:3000 -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}'
```
Following batch request failed:
```
curl -X POST -i -H 'Content-type:application/json'  http://10.1.194.183:3000 -d '[{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1},{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}]'
```
The error is:
```
curl: (52) Empty reply from server
```
Then I try to point our ethereum etl process to blutgang server:
```
"stream", "-p", "http://10.1.194.183:3000"
```
And got error on the ethereum side:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
And from blutgang side I see following error in the log:
```
thread 'tokio-runtime-worker' panicked at 'cannot access key "id" in JSON array', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.103/src/value/index.rs:102:18
thread 'tokio-runtime-worker' panicked at 'cannot access key "id" in JSON array', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.103/src/value/index.rs:102:18
Checking RPC health... OK!
thread 'tokio-runtime-worker' panicked at 'cannot access key "id" in JSON array', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.103/src/value/index.rs:102:18
```

**To Reproduce**
1. Run blutgagng
2. Make curl request 
```
curl -X POST -i -H 'Content-type:application/json'  http://10.1.194.183:3000 -d '[{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1},{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}]'
```
3. See error

Run ethereum etl and point it to blutgang server. See error.

**Expected behavior**
Batch request curl return result. 

**Specs:**
 - OS: [e.g. Ubuntu 22.04]
 - Kernel: [Linux ip-10-1-193-21 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:03 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux]
 - Blutgang version: [0.1.0]
 - Arm64 server: [Architecture: aarch64]

**Blutgang options:**
 - DB mode: [HighThroughput]
 - DB compression: [no]
 - Cache capacity: [1000000000]
 - MA length: [10]
 - RPCs used: we are using private RPC node which we are hosting ourself

**Comment by ohrab-hacken** [comment]
@makemake-kbo Thx for detailed explanation.

**Comment by makemake-kbo** [comment]
@ohrab-hacken im considering adding support for this type of batching in the next major release. do you have any other examples of tools or other various utilities that do such batching? 

It seems like a very niche feature, but if it breaks compatibility with major tooling, wallets or other infra ill add proper support for it.

**Comment by ohrab-hacken** [comment]
Hey @makemake-kbo. Thank you for your support. I've tested [web3-proxy ](https://github.com/llamanodes/web3-proxy) and [dshackle](https://github.com/emeraldpay/dshackle), both of them support batching.

**Comment by makemake-kbo** [comment]
> Hey @makemake-kbo. Thank you for your support. I've tested [web3-proxy ](https://github.com/llamanodes/web3-proxy) and [dshackle](https://github.com/emeraldpay/dshackle), both of them support batching.

Right, I'm looking at end user apps though.

If the ones that do use it are obscure or not very popular, I'm fine with being 99% JSON-RPC compliant.

**Comment by makemake-kbo** [comment]
pinging icymi @ohrab-hacken 

 
> Right, I'm looking at end user apps though.
> 
> If the ones that do use it are obscure or not very popular, I'm fine with being 99% JSON-RPC compliant.

**Comment by ohrab-hacken** [comment]
Hey @makemake-kbo. We decided to use our own proxy, so currently I have different priority and cannot test [blutgang](https://github.com/rainshowerLabs/blutgang)
