### ISSUE TITLE
Tokio panic when proxying a local (syncing/unsynced) reth node.

### ISSUE THREAD

**Issue by 8times4** [rainshowerLabs/blutgang#63]
**Describe the bug**
Tokio is panicking with value : InvalidResponse("error: Invalid response") on a local reth mainnet full node. 

**To Reproduce**
1. Run a reth full node with the configs below:
```
/usr/local/bin/reth node --full --metrics 10.0.0.4:9002 --datadir /data/reth-db/mainnet --rpc-gas-cap 18446744073709551615  --authrpc.jwtsecret /secrets/jwt.hex --authrpc.addr 127.0.0.1 --authrpc.port 8551 --http --ws --rpc-max-connections 429496729 --http.api eth,net,web3,txpool --http.addr 10.0.0.4 --http.port 8545 --ws.api net,web3,eth,txpool --ws.addr 10.0.0.4 --http.corsdomain 'https://app.example.com,moz-extension://123123123,chrome-extension://123123123'
```
2. Hook it up inside `blutgang` then start blutgang

**Expected behavior**
I expect blutgang to put the "faulty/syncing" RPC on the backburner and as if the ratelimit was hit instead of dying all at once. 

**Specs:**
 - OS: [Ubuntu 22.04]
 - Kernel: [6.5.0-1015-azure]
 - Blutgang version: [Blutgang 0.3.2 Garreg Mach - maxperf - arm64]

**Blutgang options:**
 - DB mode: [HighThroughput]
 - DB compression: [no]
 - Cache capacity: [10000000000]
 - MA length: [20]
 - RPCs used: [local reth]

**Additional context**
reth node is still syncing, - so that could be an issue, however even with a different RPC added, it does not fail over just dies. 

Logs below with the local node and merkle being added: 
```
Sorting RPCs by latency...
http://10.0.0.4:8545/: 109063.82ns
https://eth.merkle.io/: 25649351.68ns
Info: Starting Blutgang 0.3.2 Garreg Mach
Info: Bound to: 10.0.0.4:7999
Wrn: Reorg detected!
Removing stale entries from the cache.
Info: Adding user 1 to sink map
Info: Subscribe_user finding: ["newHeads"]
LA 63471.91
Info: WS request time: 17.88µs
Info: sub_id: 0x68a8ceb7a0ea6575888bd14c08f94b6c
Info: Register_subscription inserting: ["newHeads"]
Info: Subscribe_user finding: ["newHeads"]
Info: Subscribe_user finding: ["newHeads"]
Info: Checking RPC health... Wrn: http://10.0.0.4:8545/ is falling behind! Removing froma active RPC pool.
OK!
Info: Checking RPC health... OK!
Info: Checking RPC health... Info: http://10.0.0.4:8545/ is following the head again! Added to active RPC pool.
OK!
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.3.2/src/health/safe_block.rs:99:42:
called `Result::unwrap()` on an `Err` value: InvalidResponse("error: Invalid response")
stack backtrace:
   0:     0xaaaad592f7dc - std::backtrace_rs::backtrace::libunwind::trace::hee9690ac22774636
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0xaaaad592f7dc - std::backtrace_rs::backtrace::trace_unsynchronized::ha30111b5438e6e61
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaad592f7dc - std::sys_common::backtrace::_print_fmt::hc2516686a74b2a42
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0xaaaad592f7dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8984c88846573cbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaad57ad858 - core::fmt::rt::Argument::fmt::h071bdaa21123c9ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0xaaaad57ad858 - core::fmt::write::h3f4921a7ddfa57a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0xaaaad5907678 - std::io::Write::write_fmt::h0923e211983fe028
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0xaaaad5930dc0 - std::sys_common::backtrace::_print::h39d471a7e51d9dbd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaad5930dc0 - std::sys_common::backtrace::print::h6306cb106d0c42e1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaad59306b8 - std::panicking::default_hook::{{closure}}::h2a94c4f92161a016
  10:     0xaaaad593159c - std::panicking::default_hook::hd3c29c68b55e9f50
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0xaaaad593159c - std::panicking::rust_panic_with_hook::ha00bbb72a4f1b899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0xaaaad59310d8 - std::panicking::begin_panic_handler::{{closure}}::had2c64361be4b07b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0xaaaad5931040 - std::sys_common::backtrace::__rust_end_short_backtrace::hf92a1e94dde0ed69
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0xaaaad5931038 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0xaaaad568566c - core::panicking::panic_fmt::h815b849997a1324d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0xaaaad56859ac - core::result::unwrap_failed::haf618c6eb17075e2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0xaaaad573eba8 - blutgang::health::safe_block::get_safe_block::{{closure}}::{{closure}}::h7da343b20caba446
  18:     0xaaaad5702238 - tokio::runtime::task::raw::poll::h995b5616edeb2c00
  19:     0xaaaad593ea3c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h362785fb6d35bcfe
  20:     0xaaaad5944850 - tokio::runtime::task::raw::poll::h3b10e65a8244514b
  21:     0xaaaad5937608 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29cb6c7d80a2c68d
  22:     0xaaaad5937300 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2995408fccc80e98
  23:     0xaaaad593349c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he98dd9388c7047c2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  24:     0xaaaad593349c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h103af4b9c154ce59
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  25:     0xaaaad593349c - std::sys::unix::thread::Thread::new::thread_start::hc59882c1f8885c71
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  26:     0xffffad63d5c8 - <unknown>
  27:     0xffffad6a5edc - <unknown>
  28:                0x0 - <unknown>
Wrn: Timeout in newHeads subscription, possible connection failiure or missed block.
Err: Failed to get some failed node subscription IDs! Subscriptions might be silently dropped!
Wrn: Timeout in newHeads subscription, possible connection failiure or missed block.
Err: Failed to get some failed node subscription IDs! Subscriptions might be silently dropped!
Wrn: Timeout in newHeads subscription, possible connection failiure or missed block.
Err: Failed to get some failed node subscription IDs! Subscriptions might be silently dropped!
Err: No RPC position available
Info: Connection from: 10.0.0.7:47919
Info: Connection from: 10.0.0.7:36906
Info: Connection from: 10.0.0.7:61302
Info: Connection from: 10.0.0.7:23063
Info: Forwarding to: 
Info: Request time: 45.620282ms
Info: Connection from: 10.0.0.7:19736
Info: Forwarding to: 
Info: Request time: 87.366692ms
Info: Forwarding to: 
Info: Request time: 130.822258ms
Info: Forwarding to: 
Info: Request time: 172.721387ms
Info: Forwarding to: 
Info: Request time: 178.809337ms
Wrn: Timeout in newHeads subscription, possible connection failiure or missed block.
Err: Failed to get some failed node subscription IDs! Subscriptions might be silently dropped!
Wrn: Couldn't deserialize ws_conn response: Eof at character 0
```

ethspam response: 
```
(base) ➜  bin ./ethspam | ./versus --stop-after=5 --concurrency=5 https://mainnet.example.com
Endpoints:

0. "https://mainnet.example.com"

   Requests:   7.73 per second
   Timing:     0.6472s avg, 0.5578s min, 0.7360s max
               0.0627s standard deviation

   Percentiles:
     25% in 0.6495s
     50% in 0.6900s
     75% in 0.7360s
     90% in 0.7360s
     95% in 0.7360s
     99% in 0.7360s

   Errors: 100.00%
     5 × "bad status code: 500"     <--------- completely dead

** Summary for 1 endpoints:
   Completed:  5 results with 5 total requests
   Timing:     647.231558ms request avg, 1.199269542s total run time
   Errors:     5 (100.00%)
   Mismatched: 0
```

**Comment by makemake-kbo** [comment]
This is likely because blutgang is trying to get the finalized block as a part of it's reorg protection, but because reth is still syncing it's messing with it.

Could you try running either the `0.3.2-debug` docker container or compiling it with the `debug-verbose` feature so I can better understand the full picture of whats happening?

**Comment by 8times4** [comment]
Sure thing, thank you, I’ll try to do it within the next few days and let you know!

**Comment by makemake-kbo** [comment]
should be fixed in https://github.com/rainshowerLabs/blutgang/releases/tag/Blutgang-0.3.4
