### ISSUE TITLE
WS module failed trying to reinitialize

### ISSUE THREAD

**Issue by vdoflip** [rainshowerLabs/blutgang#81]
Using two Arbitrum WS endpoints (Infura and Alchemy) the WS module eventually panics and forces a restart of the container with:
```
Err: WS incoming channel closed.
thread 'tokio-runtime-worker' panicked at src/health/safe_block.rs:244:29:
FATAL: WS module failed trying to reinitialize! Please restart Blutgang!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: blutgang::main::{{closure}}::{{closure}}
   3: tokio::runtime::task::raw::poll
   4: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   5: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LA 19105.17
```

**Specs:**
 - Blutgang version: 0.3.5

**Blutgang options:**
 - DB mode:  HighThroughput
 - DB compression: no 
 - Cache capacity: 1000000000
 - MA length: ?
 - RPCs used: alchemy and infura

**Additional context**
Container running on EKS (k8s)

**Comment by taarushv** [comment]
Can also confirm this behavior, on my setup with 3x remote ethereum sepolia nodes. Would be super helpful if it failed explicitly (so that my service autorestarts) 

Version: Built off latest master branch in max perf mode.  

Context: Running it with

```
[Unit]
Description=Blutgang RPC Service
After=network.target

[Service]
Type=simple
User=root
ExecStart=/home/skypelican/.cargo/bin/blutgang -c /home/skypelican/blutgang_eth_sepolia_config.toml
Restart=on-failure
RestartSec=3s
StartLimitInterval=300s
StartLimitBurst=10

[Install]
WantedBy=multi-user.target
```


Logs: 

```
Apr 27 00:18:22 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:23 spectre blutgang[1901215]: Info: Checking RPC health... Wrn: Timeout in newHeads subscription, possible connection failiure or missed block.
Apr 27 00:18:23 spectre blutgang[1901215]: thread 'tokio-runtime-worker' panicked at /home/skypelican/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.3.5/src/websocket/client.rs:196:10:
Apr 27 00:18:23 spectre blutgang[1901215]: Failed to connect to WS: Tls(Native(Ssl(Error { code: ErrorCode(5), cause: Some(Ssl(ErrorStack([Error { code: 2147483672, library: "system library", function: "file_ctrl", file: "../crypto/bio/bss_file.c", line: 297, data: "calling fopen(/usr/lib/ssl/certs/0b9bc432.0, r)" }, Error { code: 268959746, library: "BIO routines", function: "file_ctrl", reason: "system lib", file: "../crypto/bio/bss_file.c", line: 300 }, Error { code: 92798978, library: "x509 certificate routines", function: "X509_load_cert_file_ex", reason: "system lib", file: "../crypto/x509/by_file.c", line: 100 }, Error { code: 369098857, library: "STORE routines", function: "ossl_store_get0_loader_int", reason: "unregistered scheme", file: "../crypto/store/store_register.c", line: 237, data: "scheme=file" }, Error { code: 2147483672, library: "system library", function: "file_open_dir", file: "../providers/implementations/storemgmt/file_store.c", line: 183, data: "Calling OPENSSL_DIR_read(\"/usr/lib/ssl/certs\")" }, Error { code: 2147483672, library: "system library", function: "file_ctrl", file: "../crypto/bio/bss_file.c", line: 297, data: "calling fopen(/usr/lib/ssl/certs/4042bcee.0, r)" }, Error { code: 268959746, library: "BIO routines", function: "file_ctrl", reason: "system lib", file: "../crypto/bio/bss_file.c", line: 300 }, Error { code: 92798978, library: "x509 certificate routines", function: "X509_load_cert_file_ex", reason: "system lib", file: "../crypto/x509/by_file.c", line: 100 }, Error { code: 369098857, library: "STORE routines", function: "ossl_store_get0_loader_int", reason: "unregistered scheme", file: "../crypto/store/store_register.c", line: 237, data: "scheme=file" }, Error { code: 2147483672, library: "system library", function: "file_open_dir", file: "../providers/implementations/storemgmt/file_store.c", line: 183, data: "Calling OPENSSL_DIR_read(\"/usr/lib/ssl/certs\")" }, Error { code: 369098857, library: "STORE routines", function: "ossl_store_get0_loader_int", reason: "unregistered scheme", file: "../crypto/store/store_register.c", line: 237, data: "scheme=file" }, Error { code: 2147483672, library: "system library", function: "file_open_dir", file: "../providers/implementations/storemgmt/file_store.c", line: 183, data: "Calling OPENSSL_DIR_read(\"/usr/lib/ssl/certs\")" }, Error { code: 369098857, library: "STORE routines", function: "ossl_store_get0_loader_int", reason: "unregistered scheme", file: "../crypto/store/store_register.c", line: 237, data: "scheme=file" }, Error { code: 2147483672, library: "system library", function: "file_open_dir", file: "../providers/implementations/storemgmt/file_store.c", line: 183, data: "Calling OPENSSL_DIR_read(\"/usr/lib/ssl/certs\")" }, Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1883 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })))
Apr 27 00:18:23 spectre blutgang[1901215]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 27 00:18:23 spectre blutgang[1901215]: OK!
Apr 27 00:18:24 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:24 spectre blutgang[1901215]: LA 8879.36
Apr 27 00:18:24 spectre blutgang[1901215]: Info: WS request time: 24.455µs
Apr 27 00:18:24 spectre blutgang[1901215]: Err: No ID in response: {"jsonrpc":"2.0","method":"eth_subscription","params":{"result":{"baseFeePerGas":"0x747a3","blobGasUsed":"0x60000","difficulty":"0x0","excessBlobGas":"0x4ce0000","extraData":"0xd883010d0b846765746888676f312e32312e33856c696e7578","gasLimit":"0x1c9c380","gasUsed":"0x14c9a52","hash":"0xe6b57ee0a12c92dcdf42fb5484ee7e5cf216aafc02b3f75cc143f7b1f944159b","logsBloom":"0x8404001ee02352824b3103b211101c2ac01b120171f4257262804016401b8826202980a5282c813268a4050a80d528842e8300054a4698200e885e4093fde8487371b7c67c6dae9d44638a0a0f005c2506a5a707447635cd6a0aa9408b1922fb1d00164a0769d818b81d9054015efd9e1d8880f048d2049c0228b63400190cf3ca6e6741139880e5b4a26d2b592627b120f47801160ec4f8132bb0ac45343c6ce7a8432ba604ad045559c0219800701e0842b8031c4c142a24d5d3267680000c011651638a0541b0d8190c748c3ac90299220f08984855224910d78c2a01620453d387a570e2c0889e16b113a292333e0fb0e2de4abf2a7a625b916289244401","miner":"0xc4bfccb1668d6e464f33a76badd8c8d7d341e04a","mixHash":"0x810e33ae01da00254c31d2b73851c421ef3cda12710f9a708733ef150501062e","nonce":"0x0000000000000000","number":"0x5845bb","parentBeaconBlockRoot":"0x6e8aa1a576d9e9eae486b99834aeff72357bdba63695c8f80e1318c52f984525","parentHash":"0xccb573f51f14fac76c8eaf7d9819a5e12ec3c7a5e9280cfb510df6d00c5fb375","receiptsRoot":"0x00b24c178ad15c94fed626d21f571f47004988e444c23782e1dd2b14d685c149","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","stateRoot":"0x1cae002e9f5ab810e67a8d00ac5b723d820d532d75aaf39bc8db96f7189d76c9","timestamp":"0x662c4450","transactionsRoot":"0x68439fe9eb363b5388283e0fc014f5c8580ad085ac2961f613b6dab5e98383bc","withdrawalsRoot":"0x8b204c34784dbd147269ac45e2cacd7a5241455c6325439c565efc8c5abde05d"},"subscription":"0xe013b45ff0205a3d57a600bb55f8a2a4"}}
Apr 27 00:18:24 spectre blutgang[1901215]: Info: New chain head: 5785019
Apr 27 00:18:25 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:25 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:26 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:27 spectre blutgang[1901215]: Info: Checking RPC health... OK!
Apr 27 00:18:27 spectre blutgang[1901215]: Info: Checking RPC health... Err: WS incoming channel closed.
Apr 27 00:18:27 spectre blutgang[1901215]: thread 'tokio-runtime-worker' panicked at /home/skypelican/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.3.5/src/health/safe_block.rs:244:29:
Apr 27 00:18:27 spectre blutgang[1901215]: FATAL: WS module failed trying to reinitialize! Please restart Blutgang!
Apr 27 00:18:28 spectre blutgang[1901215]: OK!
Apr 27 00:18:28 spectre blutgang[1901215]: thread 'tokio-runtime-worker' panicked at /home/skypelican/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.3.5/src/health/safe_block.rs:142:54:
Apr 27 00:18:28 spectre blutgang[1901215]: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Apr 27 00:18:31 spectre blutgang[1901215]: thread 'tokio-runtime-worker' panicked at /home/skypelican/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.3.5/src/balancer/format.rs:144:54:
Apr 27 00:18:31 spectre blutgang[1901215]: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Apr 27 00:18:36 spectre blutgang[1901215]: LA 8944.29
Apr 27 00:18:36 spectre blutgang[1901215]: Info: WS request time: 17.172µs
Apr 27 00:18:36 spectre blutgang[1901215]: Wrn: user_id 1 unsubscribed without closing channel! Removing.
```

**Comment by makemake-kbo** [comment]
This happens when blutgang tries to open a WS connection with an uncooperative/down node while it thinks its working, or if there are no WS connections to handoff subscriptions too.

I think explicitly panicking would probably be better than the current behavior while this gets fixed.

**Comment by makemake-kbo** [comment]
fixed in https://github.com/rainshowerLabs/blutgang/tree/0.4.0
